### ISSUE TITLE
Please Fix the logo

### ISSUE THREAD

**Issue by StanleyMasinde** [Opensource-254/logo254#3]
This repo should only contain one logo named logo.png
Please delete the previous logo.png and rename the logo you added to logo.png
The previous logos can be accessed via versioning. 
Click on version 1.1 to see what I mean.
Yours can then be v1.2

**Comment by conradKE** [comment]
noted wacha nifike mtaa

**Comment by conradKE** [comment]
what if we have a folder with all logos

**Comment by StanleyMasinde** [comment]
> what if we have a folder with all logos

It would mess the repo. If you want the previous logos you can access them via version control

**Comment by StanleyMasinde** [comment]
I give up.
